### ISSUE TITLE
magic numbers

### ISSUE THREAD

**Issue by nampuapx** [CalPlug/ADE7953-Wattmeter#1]
This code for 60Hz....
 You are count all channels 1 sec...

File: ADE7953.cpp
On line 264: 
```
float ADE7953::getIrmsA(){  
	unsigned long value=0;  
	value=spiAlgorithm32_read((functionBitVal(IRMSA_32,1)),(functionBitVal(IRMSA_32,0))); 
	float decimal = decimalize(value, 1327, 0);
return decimal;
```
Why 1327? 
 
On line 251: 
```
float ADE7953::getVrms(){  
	unsigned long value=0;  
	value=spiAlgorithm32_read((functionBitVal(VRMS_32,1)),(functionBitVal(VRMS_32,0)));
	float decimal = decimalize(value, 19090, 0);
return decimal;
} 
```
Why 19090? 
Are these values were obtained by fitting?
Then why the values differ in dozens of times?
Thanks

**Comment by mjklopfer** [comment]
Hi nampuapx,

Thanks for asking, we should have flagged this better.  Yes, these are the initial calibration values based on linear fitting.  Each value reported was individually regressed and linearly fit.  For a given hardware (register set) gain setting in the ADE7953 (we calibrate for each gain option in our final use code) we perform the calibration as such:


0) Set a given HW gain value - this is important, each gain needs a different calibration set typically, also beware the input impedance can change for different hardware (register set) gain values!

1) We set values to gain = 1 and offset = 0 for each channel that will be calibrated.

2) Supply a known value and record returned values for all channels we are calibrating - this may be using a load that is measured by another calibrated meter so the current and voltage (or whatever basis parameters you care about are known).

3) In MS Excel (or Origin, Matlab, or any other program that can perform linear regression), we calculate the regression values (m (gain) and b (offset)) for y=mx+b, where y is the proper value, and x is the ADC returned value.  We take a number of measurements across the linear measurement range.  Typically the ADCs on this IC are very linear.  Keep in mind the r^2 value for the fitting is not all that matters - the distance between the fit line and the expected values (the residuals) will give you an idea of calibration gross accuracy across your measurement range. 

4) Enter gain and offset regression values for each calibrated input channel (overwriting the initial gain=1 and offset=0 values used in the calibration process), recompile, and test.

5) Repeat calibration process if your outputted values do not now closely match your expected measured values.

~Mike

**Comment by mjklopfer** [comment]
Updates added to the code to clarify what the role of these values.  

Calibration is needed for each design for highest accuracy, but even for ballpark reading numbers, you may need to change them based on differences in divider resistors for the voltage channel or the load resistor/filter configuration for your current transformer circuit, or chip batches in your design.  

I flagged all the lines where calibration was used.

Note: In addition to calibration, the decimalize() function is a quick way to clean up and typecast the 2's complement math for returned signed register values into a float value in one step.   Be careful, the ADE7953 uses both 2's compliment AND sign bits for signed returned values, it is not consistent for all signed values.  Carefully check the datasheet for the registers you want to use beyond our example. 

~Mike

**Comment by miroslavpetrov** [comment]
I am trying to use your code for ADE7953 but as @nampuapx I am also having trouble understanding how the numbers used in the decimalize function are derived. I have looked at the excel table but unfortunately I cannot see there values even close to the ones used in the decimalize function. 

I am using a 1 milliohm shunt resistor in my board and I am trying to get a reasonable current readings.
